apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-fewq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-goby-tenant/rhtap-demo-app/hacbs-test-project-fewq@sha256:5f1ac16fe8a6a8612bbd3dfda8da22543e21ca25c7997e8a45283b8248283f40
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
